baseURL = "https://samsymons.com/"
title = "Sam Symons"
disableKinds = ["taxonomyTerm"]

pygmentsUseClasses = true
pygmentsCodeFences = true

[taxonomies]
  tag = "tags"

[[menu.main]]
  name = "Archive"
  identifier = "archive"
  url = "/archive/"
  weight = 1
